version: "3.4"

services:
  saleor:
    image: saleor
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    command: >
      sh -c "watchmedo auto-restart --directory=/app/saleor --pattern='*.py' --recursive --
             python -m uvicorn saleor.asgi:application --host 0.0.0.0 --port 8000 --reload"
    env_file:
      - common.env
      - backend.env
    depends_on:
      - db
      - redis
    volumes:
      - ..:/app:cached
      - ./data/python:/root/.local/share/python:cached
      - /app/.venv
      - /app/__pycache__
      - /app/*.pyc
    environment:
      - DJANGO_DEBUG=1
      - DEBUG_TOOLBAR=1
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - DJANGO_SETTINGS_MODULE=saleor.settings
      - WATCHFILES_FORCE_POLLING=true
    ports:
      - "8000:8000"
      - "5678:5678" # Debug port
    develop:
      watch:
        - action: sync
          path: ../saleor
          target: /app/saleor
          ignore:
            - "*.pyc"
            - "__pycache__"

  dashboard:
    image: ghcr.io/saleor/saleor-dashboard:3.20.5
    restart: unless-stopped
    ports:
      - 9000:80

  db:
    image: library/postgres:15-alpine
    restart: unless-stopped
    volumes:
      - saleor-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=saleor
      - POSTGRES_PASSWORD=saleor

  redis:
    image: library/redis:7.0-alpine
    restart: unless-stopped
    volumes:
      - saleor-redis:/data

  mailpit:
    image: axllent/mailpit
    ports:
      - "1025" # SMTP Server
      - "8025" # Mailpit UI
    restart: unless-stopped

  celery:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    command: watchmedo auto-restart --directory=./ --pattern=*.py --recursive -- celery -A saleor worker --loglevel=info
    volumes:
      - ..:/app:cached
    depends_on:
      - redis
      - db

volumes:
  saleor-db:
    driver: local
  saleor-redis:
    driver: local
